import json

"""
Simply returns the directories map of the project, saved in the JSON file
projectMap.JSON (generated by json_directory_map.py)
"""

def getArborescence():
    with open('/home/tom/Developpement/Git/MOwnR/Prod/Src/projectMap.JSON', 'r') as mapFile :
        outMap = json.load(mapFile)

    return outMap